### ISSUE TITLE
discord_scoreboard.smx and  discord_webhook.smx

### ISSUE THREAD

**Issue by alfari24** [devilesk/rl4d2l-plugins#2]
can give file smx please ?
discord_scoreboard.smx and  discord_webhook.smx

/// discord_scoreboard.sp
//
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : error 147: new-style declarations are required
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : error 147: new-style declarations are required
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : error 147: new-style declarations are required
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 4 Errors.
//
// Compilation Time: 0.28 sec
// ----------------------------------------

//// discord_webhook.sp
//
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : error 147: new-style declarations are required
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : error 147: new-style declarations are required
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : error 147: new-style declarations are required
// C:\Users\Administrator\Downloads\left4fun2\left4fun2\left4dead2\addons\sourcemod\scripting\include\discord_webhook.inc(6) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 4 Errors.
//
// Compilation Time: 0.2 sec
// ----------------------------------------

**Comment by devilesk** [comment]
Sure, here's both of them: [discord_webhook.zip](https://github.com/devilesk/rl4d2l-plugins/files/8934073/discord_webhook.zip)

**Comment by alfari24** [comment]
thank you sir, the plugin can be installed, I found no error log.

but End of round scores reported to discord not visible


"Discords"
{
     "discord_scoreboard"
     {
         "url" "mywebhooklink"
     }
}

**Comment by devilesk** [comment]
Do you see anything in your sourcemod logs file? And do you have the [finalemaps.ini](https://github.com/devilesk/rl4d2l-plugins/blob/master/configs/finalemaps.ini) file in your configs folder?

**Comment by devilesk** [comment]
> "Discords"
{
"discord_scoreboard"
{
"url" "mywebhooklink"
}
}

This doesn't match https://github.com/devilesk/rl4d2l-plugins/blob/master/configs/discord_webhook.cfg "Discords" should be "Discord"

**Comment by alfari24** [comment]
> Do you see anything in your sourcemod logs file? And do you have the [finalemaps.ini](https://github.com/devilesk/rl4d2l-plugins/blob/master/configs/finalemaps.ini) file in your configs folder?

yes sir, i add it "finalemaps.ini" and change Discords to Discord but still nothing happend
nothing error in logs
im using SM 11

**Comment by devilesk** [comment]
1) Do you have all the required extensions installed? You need left4dhooks, and SteamWorks extensions.

2) Do discord_scoreboard and discord_webhook appear in your plugins list on your server when you use `sm plugins list`?

3) When the plugins sends scores to discord, there should be a message in your sourcemod log file that looks something like: `L 06/16/2022 - 00:11:28: [optional/discord_webhook.smx] [InternalSendToDiscord] request {"embeds": ...`

4) Are you playing on the default campaigns or custom campaigns? Whatever maps you're playing should be in https://github.com/devilesk/rl4d2l-plugins/blob/master/configs/finalemaps.ini and https://github.com/devilesk/rl4d2l-plugins/blob/master/configs/discord_scoreboard.cfg or it won't work

**Comment by alfari24** [comment]
i have this
- [2022-06-19 10:57:02]: 031 "[L4D & L4D2] Left 4 DHooks Direct" (1.100) by SilverShot
- [2022-06-19 10:57:02]: 151 "Discord Webhook" (1.2.0) by devilesk
- [2022-06-19 10:57:02]: 152 "Discord Scoreboard" (1.4.6) by devilesk

- steamworks.ext.dll
- steamworsk.ext.so

this log error file https://mega.nz/file/2MY2AYoa#uUnE9lphau4WsR1eY148zqjokuLrgEFhSiHNTQZiS3s

im playing default campaigns

**Comment by devilesk** [comment]
What about the regular log file, not the error log file?

**Comment by alfari24** [comment]
this ? https://mega.nz/file/zVI0gRRS#6aZMqwYDttHHOvnXBgeo-EoD_26CSMO6qgK0RqWHTDs
i cant see discord log

i have Infra-DiscordChat that can running and send chat in game to discord

**Comment by devilesk** [comment]
Are you playing versus mode or some other game mode?

I've only used this plugin on Linux servers running this specific config: https://github.com/SirPlease/L4D2-Competitive-Rework so I don't know if it will work on other setups. I'd need to know more about what kind of config/plugins you're running.
